on:
  push:
    tags:
      - 'v*'

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: Run GoReleaser
            uses: goreleaser/goreleaser-action@v5
            if: startsWith(github.ref, 'refs/tags/')
            with:
              version: '~> v1'
              args: release --clean
            env:
              GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          - name: Upload assets
            uses: actions/upload-artifact@v4
            with:
              name: vault-plugin-secrets-pqm
              path: vault/plugins/*
